/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colibri;


import java.sql.*;
import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.Timer;
import java.util.TimerTask;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JRootPane;

import java.awt.event.WindowEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
/**
 *
 * @author Damiano Pareti
 */
public class Gui extends javax.swing.JFrame {
	
	/**
	 * 
	 */

	String connectionUrl = "jdbc:sqlserver://localhost:1433;" + "databaseName=AdventureWorks;integratedSecurity=true;";
    /**
     * Creates new form Gui
     */
    public Gui() {
    	setUndecorated(true);
    	setResizable(false);
    	getContentPane().setPreferredSize(new Dimension(800, 120));
    	setPreferredSize(new Dimension(800, 100));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        TxtMetri = new javax.swing.JTextField();
        TxtMetri.setPreferredSize(new Dimension(100, 60));
        TxtPeso = new javax.swing.JTextField();
        TxtPeso.setMinimumSize(new Dimension(0, 0));
        TxtPeso.setPreferredSize(new Dimension(100, 200));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        	@Override
        	public void windowOpened(WindowEvent arg0) {
        		
              /*  this.setResizable(false);
                this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
                this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
                this.setVisible(true);
        	  */
        		//Attivazione del Thread Modbus
                dModbus ModbusLoop = new dModbus();
                ModbusLoop.setDaemon(true);
                ModbusLoop.start();
                
                //Ativazione del timer di lettura ogni 100 ms
        		  new javax.swing.Timer(100, new ActionListener() {
        			     public void actionPerformed(ActionEvent e) {
        			       TxtMetri.setText(dModbus.Metri);
        			       TxtPeso.setText(dModbus.Peso);
        			     }
        			  }).start();
        		  
        		  
        	}
        });

        TxtMetri.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        TxtMetri.setText("99.00");
        TxtMetri.setName("TxtMetri"); // NOI18N

        TxtPeso.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        TxtPeso.setText("99.99");
        TxtPeso.setName("TxtPeso"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("METRI");
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("PESO");
        getContentPane().add(jLabel2);
        getContentPane().add(TxtPeso);
        getContentPane().add(jLabel1);
        getContentPane().add(TxtMetri);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
        this.setLocation(200,200);
    }//GEN-LAST:event_formComponentMoved

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
        this.setState(NORMAL);
        this.setLocation(200,200);
        this.setSize(800, 100);
    }//GEN-LAST:event_formWindowIconified

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField TxtMetri;
    private javax.swing.JTextField TxtPeso;
    // End of variables declaration//GEN-END:variables
    
   
}
