/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colibri;



import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.Timer;
import java.util.TimerTask;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JRootPane;

import java.awt.event.WindowEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
import javax.swing.JTextField;
import javax.swing.JPanel;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
/**
 *
 * @author Damiano Pareti
 */
public class Gui extends javax.swing.JFrame {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */


    public Gui() {
    	setUndecorated(true);
    	setResizable(false);
    	getContentPane().setPreferredSize(new Dimension(800, 120));
    	setPreferredSize(new Dimension(800, 100));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        	@Override
        	public void windowOpened(WindowEvent arg0) {
        		
              /*  this.setResizable(false);
                this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
                this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
                this.setVisible(true);
        	  */
        		//Attivazione del Thread Modbus
                dModbus ModbusLoop = new dModbus();
                ModbusLoop.setDaemon(true);
                ModbusLoop.start();
                
              //Attivazione del Thread Sql
                dSql SqlLoop = new dSql();
                SqlLoop.Connect();
                SqlLoop.setDaemon(true);
                SqlLoop.start();
                
                //Ativazione del timer di lettura ogni 100 ms
        		  new javax.swing.Timer(100, new ActionListener() {
        			     public void actionPerformed(ActionEvent e) {
        			    	
        			       TxtMetri.setText(dModbus.Metri);
        			       TxtPeso.setText(dModbus.Peso);
        			       TxtFlag.setText(String.valueOf(dSql.Disposizione) );
        			     }
        			  }).start();
        		  
        		  
        	}
        });
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));
        getContentPane().add(panel);
        panel.setLayout(null);
        
        textField = new JTextField();
        textField.setBounds(0, 0, 86, 20);
        panel.add(textField);
        textField.setColumns(10);
                
                label = new JLabel();
                label.setBounds(205, 39, 85, 36);
                panel.add(label);
                label.setText("PESO");
                label.setFont(new Font("Tahoma", Font.PLAIN, 36));
                jLabel2 = new javax.swing.JLabel();
                jLabel2.setBounds(741, 32, 49, 50);
                panel.add(jLabel2);
                
                        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 30)); // NOI18N
                        jLabel2.setText("Mt");
                        TxtPeso = new javax.swing.JTextField();
                        TxtPeso.setBounds(300, 39, 130, 36);
                        panel.add(TxtPeso);
                        TxtPeso.setMinimumSize(new Dimension(0, 0));
                        TxtPeso.setPreferredSize(new Dimension(100, 200));
                        
                                TxtPeso.setFont(new Font("Tahoma", Font.PLAIN, 36)); // NOI18N
                                TxtPeso.setText("99.99");
                                TxtPeso.setName("TxtPeso");
                                jLabel1 = new javax.swing.JLabel();
                                jLabel1.setBounds(499, 39, 113, 36);
                                panel.add(jLabel1);
                                
                                        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 36)); // NOI18N
                                        jLabel1.setText("METRI");
                                        
                                        TxtMetri = new javax.swing.JTextField();
                                        TxtMetri.setBounds(609, 39, 122, 38);
                                        panel.add(TxtMetri);
                                        TxtMetri.setPreferredSize(new Dimension(100, 60));
                                        
                                                TxtMetri.setFont(new Font("Tahoma", Font.PLAIN, 36)); // NOI18N
                                                TxtMetri.setText("99.00");
                                                TxtMetri.setName("TxtMetri"); // NOI18N
                                                
                                                TxtFlag = new JTextField();
                                                TxtFlag.setBounds(376, 8, 86, 20);
                                                panel.add(TxtFlag);
                                                TxtFlag.setColumns(10);
                                                
                                                JLabel label_1 = new JLabel();
                                                label_1.setText("Kg");
                                                label_1.setFont(new Font("Tahoma", Font.PLAIN, 30));
                                                label_1.setBounds(440, 39, 49, 36);
                                                panel.add(label_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
        this.setLocation(200,200);
    }//GEN-LAST:event_formComponentMoved

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
        this.setState(NORMAL);
        this.setLocation(200,200);
        this.setSize(800, 100);
    }//GEN-LAST:event_formWindowIconified

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField TxtMetri;
    private javax.swing.JTextField TxtPeso;
    private final JPanel panel = new JPanel();
    private JTextField TxtFlag;
    private JTextField textField;
    private JLabel label;
}
